// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NavigateToHandler
{
    internal sealed partial class Vsix
    {
        public const string Id = "digitaldias.NavigateToHandler.001";
        public const string Name = "Navigate to Handler";
        public const string Description = @"Adds a command that allows you to navigate to public methods across the entire solution that consume the type under the cursor as a parameter. ";
        public const string Language = "en-US";
        public const string Version = "0.9";
        public const string Author = "digitaldias";
        public const string Tags = "";
    }
}
